### ISSUE TITLE
git Config file please!

### ISSUE THREAD

**Issue by ArunGaurav** [Vitriol1744/Vortex#2]
Hi, sorry this isn't an issue, but since you've made this project open source, i dont think asking for your git config file is restricted...
I want to check something in that for educational purposes, so can you please attach that as a reply to this comment!
Thanks!

**Comment by Vitriol1744** [comment]
Are u asking for this?

[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/vitriol1744/Vortex
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[submodule "Vortex-Engine/vendor/imgui"]
        url = https://github.com/vitriol1744/imgui
        active = true

**Comment by Vitriol1744** [comment]
[config.zip](https://github.com/Vitriol1744/Vortex/files/7007330/config.zip)

Are u asking for this?

**Comment by ArunGaurav** [comment]
yes and thank you!
